server:
  port: 40004
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
#    trust-store: classpath:truststore.p12
#    trust-store-password: changeit
#    client-auth: need
  http2:
    enabled: true
springdoc:
  show-actuator: true
management:
  endpoint:
    health:
      show-details: always
      show-components: always
spring:
  security:
    user:
      name: admin
      password: password
  cache:
    type: caffeine
    cache-names: cartCache
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=15m
  application:
    name: active-life-canada-app
  datasource:
    url: jdbc:postgresql://localhost:5432/active_life_canada
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
ems:
  api:
    base-url: http://localhost:8080/api/v1
logging:
  level:
    root: error
    org.springframework: info
    org.springframework.security: trace
    io.reactivestax.active.life.canada: info
stripe:
  api:
    baseUrl: https://api.stripe.com/v1
    key: ${STRIPE_SECRET_KEY}