server:
  port: 8082
spring:
  cache:
    type: caffeine
    cache-names: cartCache
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=15m
  application:
    name: active-life-canada-app
  datasource:
    url: jdbc:postgresql://localhost:5432/active_life_canada
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
ems:
  api:
    base-url: http://localhost:8080/api/v1
logging:
  level:
    root: INFO
stripe:
  api:
    baseUrl: https://api.stripe.com/v1
    key: ${STRIPE_SECRET_KEY}