server.port: 8082
spring:
  application:
    name: active-life-canada-app
    cacheName: cartCache
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=15m,refreshAfterWrite=15m
      cache-names:
        - cartCache
  datasource:
    url: jdbc:postgresql://localhost:5432/active_life_canada
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql=true:
logging:
  level:
    root: INFO
ems:
  api:
    baseUrl: http://localhost:8080/api/v1
#stripe:
#  api:
#    baseUrl: https://api.stripe.com/v1
#    key: ${STRIPE_SECRET_KEY}
