file.path=src/main/resources/trades.csv
chunk.directory.path=src/main/resources/chunks
chunk.file.path=src/main/resources/chunks/trade_records_chunk
db.driver.class=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/hibernate_trade_processor
db.username=root
db.password=password123
chunks.count=10
chunk.processor.thread.count=10
queue.count=2
trade.distribution.criteria=accountNumber
trade.distribution.use.map=false
trade.distribution.algorithm=random
activemq.broker.url=tcp://localhost:61616
activemq.username=admin
activemq.password=admin
activemq.topic=trading